version: "3.8"

services:
  frontend:
    build: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - frontend
